debug: false

ssl: false

sentry:
  active: false

server:
  port: 8080

elasticSearch:
  urls: http://134.209.29.25:9200
  sniff: false
  healthCheck: true

Networks:
  - name: mainnet

    host: navcoind.navexplorer.com
    port: 8332
    username: user
    password: password

    communityFund:
      blocksInCycle: 20160
      minQuorum: 0.5
      proposalVoting:
        cycles: 4
        accept: 0.7
        reject: 0.7
      paymentVoting:
        cycles: 4
        accept: 0.7
        reject: 0.7

    softFork:
      blocksInCycle: 20160
      accept: 0.75

  - name: testnet

    host: testnet.navexplorer.com
    port: 8332
    username: user
    password: password

    communityFund:
      blocksInCycle: 180
      minQuorum: 0.5
      proposalVoting:
        cycles: 4
        accept: 0.7
        reject: 0.7
      paymentVoting:
        cycles: 4
        accept: 0.7
        reject: 0.7

    softFork:
      blocksInCycle: 400
      accept: 0.75